# Generated by Django 5.0.6 on 2024-08-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumb',
            field=models.ImageField(blank=True, default='defaault_image.png', upload_to=''),
        ),
    ]
