# Generated by Django 5.0.6 on 2024-09-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
